### ISSUE TITLE
Add file logging option for webrtc canary

### ISSUE THREAD

**Issue by disa6302** [aws-samples/amazon-kinesis-video-streams-demos#112]
We log to cloudwatch with the canary app. But, we should also add a certain degree of redundancy in logging to ensure we have a backup of logs in the device running the canary. We must look into adding a file logging option along with cloudwatch.

Discussion reference: #111

**Comment by lherman-cs** [comment]
@disa6302 I'm not sure why this is needed. Jenkins already preserves the logs, adding more file logging will only duplicate it, worsen the storage space issue. Since we only keep X amounts of builds, the file logs that we want to add will also be deleted.

You can avoid the file logs from being deleted, but this needs to mutate the system, which is dangerous and you need to go out of the sandbox.

**Comment by MushMal** [comment]
Sounds good then

**Comment by disa6302** [comment]
Closing this based on offline discussion. 
Moving to a system with larger memory helps for our use case.
