### ISSUE TITLE
error in aws kinesis stream setup in raspberry pi with docker file

### ISSUE THREAD

**Issue by yogii786** [aws-samples/amazon-kinesis-video-streams-demos#211]
sudo docker run -it --device=/dev/video0 --device=/dev/vchiq -v /opt/vc:/opt/vc <image-id> /bin/bash

during running this command in raspberry pi4  Iam getting this error
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
docker: Error response from daemon: error gathering device information while adding custom device "/dev/video0": no such file or director
![Screenshot from 2021-12-14 17-13-04](https://user-images.githubusercontent.com/57557160/145992555-cf7ffa57-a8f6-4c12-b4dd-30dab391abc4.png)

**Comment by sirknightj** [comment]
Due to the CPU architecture, you may need to add the platform argument to the docker run command. Docker usually does this for you, but sometimes it gets it wrong.
```
--platform linux/arm/v7
```
Put that right after "docker run". Also note that it's just a warning from docker.

As for the other issue about video0, please make sure that the camera is connected to the raspberry pi, and the number is correct.
Try running `ls /dev/video*` or:
```
sudo apt-get install v4l-utils
v4l2-ctl --list-devices
```

Note that our raspberry pi documentation has recently been updated, so you may want to refer to that as well: https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producersdk-cpp-rpi.html

Please reach out if you have any further questions!
